H/w lesson 5 was added
SubochevaValeriya/Go-Level-2 pull request #5
Opened 2022-09-11 11:08 UTC by SubochevaValeriya

h/w lesson 5 was added

2022-09-11 15:21 UTC, rowdyroad requested changes

2022-09-11 15:21 UTC, rowdyroad commented on lesson-5/main.go
> +			wg.Done()
лучше делать defer wg.Done(), иначе при большом количестве строк в функции можно этот вызов потерять

2022-09-11 15:21 UTC, rowdyroad commented on lesson-4/main.go
> +func sigterm() {
не то сделано, читать тут: https://gobyexample.com/signals

2022-09-12 21:32 UTC, merged

2022-09-12 21:32 UTC, SubochevaValeriya commented on lesson-4/main.go
> +func sigterm() {
Спасибо! Я поправила.